title = "Config"

[cytomine]
dataset_path = "../datasets/LBTD/"
project_id = '10688948'
annotation_user_id = '10695763'
ROI_term_id = '25635386'
random_shift = 0
random_state = 42
zoom_out_factor = 2.0  # Zoom out factor for the crop around the annotation, 1.0 means no zoom out

[sam]
model_type = 'vit_b'    #'vit_b', 'vit_l', 'vit_h'
checkpoint_path = '../checkpoints/sam_vit_b_01ec64.pth'
device = 'cuda'
input_size = 1024

[dataset]
points = true
negative_points = false
box = true
negative_points_inside_box = true
n_points = 5
points_near_center = -1 # The higher the value, the closer to the center of mask the points have a chance to be. -1 means no restriction
box_size = 1.0
random_box_shift = 0 # Random shift in the box position in pixels (simulates the annotation error of an expert)

[training]
batch_size = 2
