wandb_version: 1

title:
  desc: null
  value: Config
cytomine:
  desc: null
  value:
    dataset_path: ../datasets/merged/
    project_id: '54149054'
    annotation_users_id:
    - '23245043'
    - '35984253'
    ROI_term_id: '25635386'
    random_shift: 0
    random_state: 42
    zoom_out_factor: 2.0
sam:
  desc: null
  value:
    model_type: vit_b
    checkpoint_path: ../checkpoints/sam_vit_b_01ec64.pth
    input_size: 1024
dataset:
  desc: null
  value:
    points: true
    negative_points: true
    box: true
    mask_prompt: true
    negative_points_inside_box: true
    n_points: 1
    n_neg_points: 10
    points_near_center: 4
    box_size: 1.0
    random_box_shift: 20
    mask_prompt_type: scribble
    box_around_prompt_mask: false
evaluate:
  desc: null
  value:
    input_mask_eval: false
training:
  desc: null
  value:
    batch_size: 4
    epochs: 100
    eval_every_epoch: true
    splits:
    - 0.8
    - 0.2
    lr: 1.0e-05
    use_img_embeddings: true
    model_save_dir: ../checkpoints/train/
    train_from_last_checkpoint: false
misc:
  desc: null
  value:
    device: cuda
    wandb: true
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1717396820.992534
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 100
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 100
      3:
      - 16
      - 23
      4: 3.11.4
      5: 0.15.4
      8:
      - 2
      - 3
      - 5
